---
- hosts: winhost
  gather_facts: no
  tasks:

   - name: Install Chocolatey on Windows10
     win_chocolatey: name=procexp  state=absent
   - name: Install 7Zip Archive Software
     win_chocolatey: name=7zip state=absent
